<?php

namespace App\Controller\Admin;

use App\Entity\Car;
use App\Entity\ContactMessage;
use App\Entity\ContactMessageCar;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TelephoneField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ContactMessagesCrudController extends AbstractCrudController
{
    public function __construct( private EntityManagerInterface $entityManager ){}

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Message')
            ->setDefaultSort(['createdAt' => 'DESC'])
            ->setEntityLabelInPlural('Messages')
            ->setPageTitle('index', 'Liste des messages')
            ->setPaginatorPageSize(10)
            ->showEntityActionsInlined()
            ->setDefaultSort(['createdAt' => 'DESC'])
            ->setPageTitle(Crud::PAGE_DETAIL, function($message){ return 'Demande de ' . $message->getFullname();})
            ;
    }

    public static function getEntityFqcn(): string { return ContactMessage::class;}
    public function configureFields(string $pageName): iterable
    {
        yield TextField::new('fullname')->setLabel('Nom complet')
            ->formatValue(function ($value, $contactMessage) {
                return !$contactMessage->isIsReadByStaff() ? "⚠️ {$value}" : $value;
            });
        yield EmailField::new('email')->setLabel('Email');
        yield TelephoneField::new('phoneNumber')->setLabel('Téléphone');
        yield TextField::new('subject')->setLabel('Objet du message');
        yield AssociationField::new('concernedCar', 'Véhicule concerné')
            ->setTemplatePath('admin/field/car/detail/car.html.twig')
            ->setSortable(false)
//            ->setSortable(false)
//            ->setTemplatePath('@EasyAdmin/crud/detail.html.twig')
        ;
        yield TextField::new('message', 'Message');
        yield DateField::new('createdAt', 'Crée le')
            ->setSortable(true)
            ->setFormat('dd/MM/yyyy à HH:mm')
        ;
        yield TextField::new('createdBy')->setLabel('Crée par')->onlyOnDetail();
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions
            ->disable(Action::NEW, Action::EDIT)
            ->set(Crud::PAGE_INDEX, Action::DETAIL)
            ->update(Crud::PAGE_INDEX, Action::DETAIL, fn ($action) => $action->setLabel('Voir'))
            ->update(Crud::PAGE_INDEX, Action::DELETE, fn ($action) => $action->setLabel('Supprimer'))
            ->update(Crud::PAGE_DETAIL, Action::DELETE, fn ($action) => $action->setLabel('Supprimer'))
            ->update(Crud::PAGE_DETAIL, Action::INDEX, fn ($action) => $action->setLabel('Retour'))
        ;
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $currentUser = $this->getUser();
        $entityInstance->setCreatedBy($currentUser->getFullname());
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function detail(AdminContext $context)
    {
        /** @var ContactMessage $contactMessage */
        $contactMessage = $context->getEntity()->getInstance();
        if (!$contactMessage->isIsReadByStaff()) {
            $contactMessage->setIsReadByStaff(true);
            $this->entityManager->persist($contactMessage);
            $this->entityManager->flush();
        }
        return parent::detail($context); // TODO: Change the autogenerated stub
    }

}
